function visualizeAAE_EPE( gr_uv, uv, slice, rangeVelecity, rangeAngle )

    epe_err = ( gr_uv(:,:,slice,1)-uv(:,:,slice,1) ).^2 + ...
              ( gr_uv(:,:,slice,2)-uv(:,:,slice,2) ).^2 + ...
              ( gr_uv(:,:,slice,3)-uv(:,:,slice,3) ).^2;
    figure
    imshow( sqrt(epe_err), rangeVelecity, 'init', 'fit'); colormap jet

    
    ang_err = acos( ( gr_uv(:,:,slice,1).*uv(:,:,slice,1) + ...
                      gr_uv(:,:,slice,2).*uv(:,:,slice,2) + ...
                      gr_uv(:,:,slice,3).*uv(:,:,slice,3) )...
                    ./ ...
(sqrt( gr_uv(:,:,slice,1).^2 + gr_uv(:,:,slice,2).^2 + gr_uv(:,:,slice,3).^2 )... 
.* sqrt( uv(:,:,slice,1).^2 + uv(:,:,slice,2).^2 + uv(:,:,slice,3).^2) ) );
    
    figure
    imshow( ang_err*180/pi, rangeAngle, 'init', 'fit'); colormap jet
end